from datetime import date

# Constants
DEFAULT_TICKERS = ["BTC-USD", "ETH-USD", "^GSPC", "^NDX", "QQQ3.L", "3USL.L", "AAAU"]
DEFAULT_START_DATE = date(2022, 1, 1)
DEFAULT_INITIAL_INVESTMENT = 100
DEFAULT_PERIODIC_INVESTMENT = 100
